# Generated by Django 5.1.1 on 2024-10-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='housenumber',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='street',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detailed_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='diets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dining_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='meal_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ranking',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews_per_rating',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='top_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
