# Generated by Django 5.1.2 on 2024-10-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_amenity_remove_restaurant_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='reviews',
            new_name='reviews_count',
        ),
    ]
