# Generated by Django 5.1.1 on 2024-10-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_amenity_remove_restaurant_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='top_tags',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, to='restaurants.cuisine'),
        ),
    ]
