# Generated by Django 5.1.1 on 2024-11-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_reviews_restaurant_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
