# Generated by Django 5.1.1 on 2024-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_cuisine_remove_restaurant_top_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='top_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
