# Generated by Django 5.1.1 on 2024-10-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
